title: "slama.dev"
description: "Tomáš Sláma's personal website."
url: "http://localhost:4000"

baseurl: ""
markdown: kramdown

# exclude Jekyll-related files, scripts and generated content
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "s-theme.gemspec",
  "ignored/",
  "scripts/",
  "makefile",
  "LICENSE.txt",
  "README.md",
]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /:slugified_categories/:title/
