title: "slama.dev"
description: "Tomáš Sláma's personal website."
url: "https://slama.dev"

baseurl: ""

# exclude Jekyll-related files, scripts and generated content
exclude: [
  "ignored/",
  "scripts/",
  "makefile",
  "LICENSE.txt",
  "**/README.md",
  "README.md",
]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /:slugified_categories/:title/
